### ISSUE TITLE
demo url please

### ISSUE THREAD

**Issue by johnfelipe** [IndignatsCardedeu/OpenPlenary#1]
demo url please
tnks

**Comment by johnfelipe** [comment]
Demo pls

**Comment by IndignatsCardedeu** [comment]
We are working on it, in a week or two we will publish a demo site.

**Comment by johnfelipe** [comment]
have u, screenshots or something?

**Comment by johnfelipe** [comment]
Nothing yet

**Comment by johnfelipe** [comment]
Do u have screenshots?

**Comment by johnfelipe** [comment]
Hi again, pls share me demo url, tnks

**Comment by IndignatsCardedeu** [comment]
Sorry for the BIG delay, here you have a demo URL with some data pre-loaded in catalan language.
http://demo.plensoberts.cat/
